library/urls.py
from django.contrib import admin
from django.urls import path, include

from todolist import views

urlpatterns = [
    path('', views.go_to_home, name='go_to_home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls, name='admin_page'),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path

from .views import *

app_name = 'todolist'

urlpatterns = [
    # path('task/', task_list, name='task_list'),
    # path('list/', display_list_of_task_lists, name='display_task_lists'),
    # path('list_content/<int:task_list_id>', open_list, name='go_to_list_content'),
    # path('task_desc/<int:task_id>', display_task_detail, name='go_to_description'),
    # path('delete/<int:task_id>', delete_task, name='delete'),
    # path('manage/', task_manager, name='create'),
    # path('manage/<int:task_id>', task_manager, name='update'),

    path('task/', TaskListView.as_view(), name="task_list"),
    path('task_desc/<int:pk>', TaskDetailView.as_view(), name="go_to_description"),
    path('create', TaskCreateView.as_view(), name="create"),
    path('edit/<int:pk>', TaskEditView.as_view(), name="edit"),
    path('delete/<int:pk>', TaskDeleteView.as_view(), name="delete"),

    path('list/', ListListView.as_view(), name="list-list"),
    path('list/detail/<int:pk>', ListDetailView.as_view(), name="list-detail"),
    path('list/create', ListCreateView.as_view(), name="list-create"),
    path('list/edit/<int:pk>', ListEditView.as_view(), name="list-edit"),
    path('list/delete/<int:pk>', ListDeleteView.as_view(), name="list-delete"),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User


class TaskList(models.Model):
    list_title = models.CharField(max_length=100,
                                  verbose_name="List Title",
                                  null=False,
                                  blank=False,
                                  editable=True)
    list_users = models.ManyToManyField(to=User,
                                        related_name='lists')

    def __str__(self):
        return self.list_title


class Task(models.Model):
    task_name = models.CharField(max_length=200,
                                 verbose_name="Task Name",
                                 null=False,
                                 blank=False,
                                 editable=True)

    task_description = models.TextField(verbose_name="Task Description",
                                        default="Ajouter une description")

    task_due_date = models.DateField(verbose_name="Task Deadline")
    task_time = models.DurationField(verbose_name="Task Duration")

    task_ended = models.BooleanField(verbose_name="Is Done ?",
                                     default=False)

    task_priority = models.IntegerField(verbose_name="Priority",
                                        choices=((1, "High"), (2, "Medium"), (3, "Low"),),
                                        default=3)
    task_list = models.ForeignKey(to=TaskList,
                                  related_name='tasks',
                                  on_delete=models.SET_NULL,
                                  null=True)

    def __str__(self):
        return '{} {}'.format(self.task_name, self.task_due_date)

todolist/forms.py
from django import forms
from .models import Task


class NewTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'


def __init__(self):
    self.priority = 3

todolist/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import resolve_url
from django.contrib.auth import user_logged_in
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView

from .models import Task, TaskList
from .forms import NewTaskForm


def go_to_description(task_id):
    return HttpResponseRedirect(reverse('todolist:display_task_detail', kwargs={'task_id': task_id}))


def go_to_list_content(task_id):
    return HttpResponseRedirect(reverse('todolist:open_list', kwargs={'task_list_id': task_id}))


@login_required
def go_to_home(request):
    return HttpResponseRedirect(reverse('todolist:list-list'))


def go_to_admin(request):
    return HttpResponseRedirect(reverse('admin'))


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    fields = '__all__'
    success_url = reverse_lazy('todolist:list-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Create'
        return context


class TaskEditView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Update'
        return context


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'todolist/task_list.html'
    context_object_name = 'tasks'


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'todolist/task_detail.html'


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = 'todolist/task_delete.html'


class ListListView(LoginRequiredMixin, ListView):
    model = TaskList
    template_name = 'todolist/task_list_list.html'


class ListDetailView(LoginRequiredMixin, DetailView):
    model = TaskList
    template_name = 'todolist/task_list_detail.html'


class ListCreateView(LoginRequiredMixin, CreateView):
    model = TaskList
    fields = '__all__'
    template_name = 'todolist/task_form.html'
    success_url = reverse_lazy('todolist:list-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Create'
        return context


class ListEditView(LoginRequiredMixin, UpdateView):
    model = TaskList
    fields = '__all__'
    template_name = 'todolist/task_form.html'
    success_url = reverse_lazy('todolist:list-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Update'
        return context


class ListDeleteView(LoginRequiredMixin, DeleteView):
    model = TaskList
    template_name = 'todolist/task_list_delete.html'
    success_url = reverse_lazy('todolist:list-list')


# def task_manager(request, task_id=None):
#     if task_id:
#         task = Task.objects.get(pk=task_id)
#
#         form = NewTaskForm(request.POST or None,
#                            instance=task)
#         action = 'Update'
#     else:
#         form = NewTaskForm(request.POST or None)
#         action = 'Create'
#
#     if form.is_valid():
#         form.save()
#
#     return render(request=request,
#                   template_name='todolist/task_form.html',
#                   context={'form': form,
#                            'action': action})
#
#
# def delete_task(request, task_id):
#     Task.objects.get(pk=task_id).delete()
#     return HttpResponseRedirect(reverse('todolist:task_list'))
#
#
# def task_list(request):
#     tasks = Task.objects.all()
#
#     context = {'tasks': tasks}
#
#     return render(request=request,
#                   template_name='todolist/task_list.html',
#                   context=context)
#
#
# def display_list_of_task_lists(request):
#     task_lists = TaskList.objects.all()
#
#     context = {'task_lists': task_lists}
#
#     return render(request=request,
#                   template_name='todolist/task_list_tasks.html',
#                   context=context)
#
#
# def display_task_detail(request, task_id):
#     task_to_display = Task.objects.get(pk=task_id)
#
#     context = {'task': task_to_display}
#
#     return render(request=request,
#                   template_name='todolist/task_detail.html',
#                   context=context)
#
#
# def open_list(request, task_list_id):
#     list_to_open = TaskList.objects.get(pk=task_list_id)
#
#     context = {'task_list': list_to_open}
#
#     return render(request=request,
#                   template_name='todolist/task_list_content.html',
#                   context=context)

todolist/templates/base.html
<!doctype html>
<html lang="en">

      <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/lux/bootstrap.min.css" crossorigin="anonymous">

          {% block title %}

          {% endblock %}
      </head>

      <body>
      {% include 'menu.html' %}
      <div class="container">
          {% block content %}
          {% endblock %}
      </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      </body>

</html>

todolist/templates/date_picker.html
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 4 DatePicker</title>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <input id="datepicker" width="276" />
    <script>
        $('#datepicker').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>
</body>
</html>

todolist/templates/menu.html
<!doctype html>
<html lang="en">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'todolist:list-list' %}">
          <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1024px-Python-logo-notext.svg.png" width="30" height="30" class="d-inline-block align-top" alt="">
          Task Manager
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        {% if user.is_authenticated %}
          <dt class="nav-item active">
            <a class="nav-link" href="#">Admin <span class="sr-only">(current)</span></a>
          </dt>

            <ul class="navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Tools
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'todolist:create' %}">Create Task</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'todolist:list-create' %}">Create List</a>
                </div>
              </li>
            </ul>
        {% endif %}

        {% if not user.is_authenticated %}
          <dt class="nav-item active">
            <a class="nav-link" href="{% url 'login' %}">Login <span class="sr-only">(current)</span></a>
          </dt>
        {% else %}
          <dt class="nav-item active">
            Bienvenue {{ user }}
            <a class="nav-link" href="{% url 'logout' %}">Logout <span class="sr-only">(current)</span></a>
          </dt>
        {% endif %}

      </div>
    </nav>
</html>

todolist/templates/popup.html
<div class="modal fade" id="{% url 'todolist:display_task_lists' task_id=task.pk %}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          {% block content %}
          {% endblock %}
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary" href="{% url 'todolist:update' task_id=task.pk %}"> Update Task </a>
        <a class="btn btn-primary" href="{% url 'todolist:delete' task_id=task.pk %}"> Delete Task </a>
      </div>
    </div>
  </div>
</div>

todolist/templates/todolist/task_delete.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<form method="post">
    Etes-vous sur ?
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Confirm">
</form>

{% endblock %}

todolist/templates/todolist/task_detail.html
{% extends "base.html" %}

{% block content %}

<head>
    <meta charset="UTF-8">
    <title>{{ task.task_name }}</title>
</head>

    <h2>{{ task.task_name }}</h2>

    <dl>
        <dt>Desciption: </dt>
        <dd> {{ task.task_description|linebreaksbr }}</dd>
        <dt>Due Date: </dt>
        <dd>{{ task.task_due_date }}</dd>
        <dt>Expected Time: </dt>
        <dd>{{ task.task_time }}</dd>
        <dt>Is Terminated: </dt>
        <dd>{{ task.task_ended }}</dd>
        <dt>Priority: </dt>
        <dd>{{ task.task_priority }}</dd>
    </dl>

<a class="btn btn-primary" href="{% url 'todolist:edit' pk=task.pk %}"> Update Task </a>
<a class="btn btn-primary" href="{% url 'todolist:delete' pk=task.pk %}"> Delete Task </a>

{% endblock %}

todolist/templates/todolist/task_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
<!--{% load static %}-->

<!--<script src="{% static 'ContactFrom_v1/js/main.js' %}"></script>-->
<!--<link href="{% static 'css/main.css' %}" rel="stylesheet">-->


{% block content %}

<form method="post">
    {% csrf_token %}
<!--    {% include 'date_picker.html' %}-->
    {% bootstrap_form form %}
    <input type="submit" value="{{ action }}">
</form>

{% endblock %}

todolist/templates/todolist/task_list.html
{% extends "base.html" %}

{% block content %}

<head>
    <meta charset="UTF-8">
    <title>HomePage</title>
</head>

<body>
    {% if tasks %}
    <h2>Tasks list :</h2>
        <ul>
            {% for task in tasks %}
                <li>
                    {{ task }}
<!--                    <a  class="btn btn-primary" href="#{% url 'todolist:go_to_description' task_id=task.pk %}" >-->
<!--                        Show-->
<!--                    </a>-->
                    <a href="{% url 'todolist:go_to_description' task_id=task.pk %}"> show</a>
                </li>
            {% endfor %}
        </ul>

    {% else %}
        <p>
            Nothing planed.
        </p>
    {% endif %}

</body>

{% endblock %}

todolist/templates/todolist/task_list_content.html
<!--{% extends "base.html" %}-->

<!--{% block content %}-->

<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>{{ task_list.list_title }}</title>-->
<!--</head>-->

<!--    <h2>{{ task_list.list_title }}</h2>-->

<!--    <ul>-->
<!--        <li>-->
<!--            {{ task_list.my_tasks.all() }}-->
<!--        </li>-->
<!--    </ul>-->

<!--{% endblock %}-->

todolist/templates/todolist/task_list_delete.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<form method="post">
    Etes-vous sur ?
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Confirm">
</form>

{% endblock %}

todolist/templates/todolist/task_list_detail.html
{% extends "base.html" %}

{% block content %}

<head>
    <meta charset="UTF-8">
    <title>{{ object.list_title }}</title>
</head>

    <h2>{{ object.list_title }}</h2>

    <ul>
        {% comment %}
        {{ object.tasks.all|join:"<br>" }}
        <a href="{% url 'todolist:go_to_description' pk=obj.pk %}">Show</a>
        {% endcomment %}
            {% for obj in object.tasks.all %}
                {{ obj }}
                <a href="{% url 'todolist:go_to_description' pk=obj.pk %}">Show</a>
            <br>
            {% endfor %}
    </ul>

    <a class="btn btn-primary" href="{% url 'todolist:list-edit' pk=object.pk %}"> Update List </a>
    <a class="btn btn-primary" href="{% url 'todolist:list-delete' pk=object.pk %}"> Delete List </a>

{% endblock %}

todolist/templates/todolist/task_list_list.html
{% extends "base.html" %}

{% block content %}

<head>
    <meta charset="UTF-8">
    <title>HomePage</title>
</head>

<body>
    {% if object_list %}
    <h2>Available lists :</h2>
        <ul>
            {% for list in object_list %}
                <li>
                    {{ list }}

                    <a href="{% url 'todolist:list-detail' pk=list.pk %}"> Open</a>
                </li>
            {% endfor %}
        </ul>

    {% else %}
        <p>
            Nothing planed.
        </p>
    {% endif %}

</body>

{% endblock %}

todolist/templates/todolist/task_list_tasks.html
{% extends "base.html" %}

{% block content %}

<head>
    <meta charset="UTF-8">
    <title>HomePage</title>
</head>

<body>
    {% if task_lists %}
    <h2>Available lists :</h2>
        <ul>
            {% for task_list in task_lists %}
                <li>
                    {{ task_list }}

                    <a href="{% url 'todolist:go_to_list_content' task_list_id=task_list.pk %}"> Open</a>
                </li>
            {% endfor %}
        </ul>

    {% else %}
        <p>
            Nothing planed.
        </p>
    {% endif %}

</body>

{% endblock %}

todolist/templates/todolist/task_list_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>